### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by dfaofeng** [Darren-chenchen/flutter_flowermusic#6]
错误代码 `* What went wrong:
Execution failed for task ':app:preDebugBuild'.’
> Android dependency 'androidx.vectordrawable:vectordrawable' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution`
AS版本
![批注 2019-12-12 000945](https://user-images.githubusercontent.com/14891398/70638367-b9aa8b80-1c73-11ea-9479-2fd943af3be4.png)

**Comment by liuzhiheng126** [comment]
android/app/build.gradle文件的依赖里面添加
implementation 'androidx.appcompat:appcompat:1.0.2'
用这个显示指定一下依赖

**Comment by liuzhiheng126** [comment]
implementation 'androidx.vectordrawable:vectordrawable:1.0.1'

**Comment by dfaofeng** [comment]
implementation 'androidx.appcompat:appcompat:1.0.2' 用了这个解决了,
![Screenshot_2019-12-12-13-21-12](https://user-images.githubusercontent.com/14891398/70684791-50159600-1ce2-11ea-9374-52ebdd897e38.png)底栏显示超出了

**Comment by Darren-chenchen** [comment]
嗯，细节问题可以自己适配，请重点关注总体架构
